[files]
extend-exclude = [
    "tests/facts/apt.SimulateOperationWillChange/upgrade.json",
    "tests/words.txt",
]

[default]
extend-ignore-re = [
    "shell\\('uptim'\\)",
    '"fpr:::::::::',
    '== "fpr":',
    "00740ba1",
    "forr something in",
    "unknown tag 'forr'",
    "nd6 options=",
]

[default.extend-words]
datas = "datas"
